### ISSUE TITLE
Create a project template for large scale biostats projects to be used create_msk_project()

### ISSUE THREAD

**Issue by karissawhiting** [ddsjoberg/bstfun#2]
Template will include explicit folder structure for data cleaning and reporting pipelines including folders like `raw-data`, `data`, `scripts`, `outputs`, etc.

**Comment by ddsjoberg** [comment]
@karissawhiting is this something you still plan on doing? should i keep it open or close it?

**Comment by ddsjoberg** [comment]
I am going to close this for now, but feel free to open if you want to add something
