### ISSUE TITLE
Feature request: Allow bolding and italicizing for group's headers 

### ISSUE THREAD

**Issue by oranwutang** [ddsjoberg/bstfun#65]
Hi there!

In stacked tables there is an option to add headers for each table (group_header argument in tbl_stack()), but those labels can't be easily modified to set them in bold or italics. It would be nice to have a function like:

stacked_table %>%
 bold_groupheaders()

Similar to bold_labels()

Thanks in advance and best regards!

**Comment by ddsjoberg** [comment]
merged!
